#!/bin/sh
cd ${0%/*} || exit 1    # Run from this directory

# Parse arguments for library compilation
. $WM_PROJECT_DIR/wmake/scripts/AllwmakeParseArguments

# Compile pfmFOAM libraries and applications
src/Allwmake $targetType $*

# Compile pfmFOAM libraries and applications
applications/Allwmake $targetType $*

#------------------------------------------------------------------------------
