#!/bin/sh

# Source tutorial clean functions
. $WM_PROJECT_DIR/bin/tools/CleanFunctions

cleanCase

rm constant/cellDist
rm constant/rMesh/cellDist

sed -i -e 's/manual;/scotch;/g' system/decomposeParDict
sed -i -e 's/manual;/scotch;/g' system/rMesh/decomposeParDict

