#!/bin/sh
# Source run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

rm -r 0
cp -r orig.0 0


m4 -P system/blockMeshDict.m4 > system/blockMeshDict
m4 -P system/rMesh/blockMeshDict.m4 > system/rMesh/blockMeshDict

blockMesh
mirrorMesh -overwrite

blockMesh -region rMesh

decomposePar -cellDist
decomposePar -region rMesh -cellDist
rm -r processor*

setFields
setFields -region rMesh
./preDecompose.sh

sed -i -e 's/scotch/manual/g' system/decomposeParDict
sed -i -e 's/scotch/manual/g' system/rMesh/decomposeParDict

decomposePar -cellDist
decomposePar -region rMesh -cellDist

runParallel pisoFoam

reconstructPar
reconstructPar -region rMesh
