#!/bin/sh
. $WM_PROJECT_DIR/bin/tools/RunFunctions

cp -rf 0.orig 0

# create mesh
runApplication blockMesh

# set initial conditions
runApplication setFields

# decompose domain
runApplication decomposePar

# run twoPhaseEulerTurbFoam
runParallel $(getApplication)

