#!/bin/sh
cd ${0%/*} || exit 1    # Run from this directory

# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

cp -r 0.orig 0

application=$(getApplication)

./makeMesh

runApplication decomposePar
runParallel $application
runApplication reconstructPar
runApplication vectorSnapshots

#------------------------------------------------------------------------------

